# A URL com o prefixo jdbc:
spring.datasource.url=jdbc:postgresql://localhost:5433/meu_evento_db

spring.datasource.driver-class-name=org.postgresql.Driver

# O usuário que veio na sua string
spring.datasource.username=postgres

# Substitua pela sua senha real, SEM os colchetes []
spring.datasource.password=root

# --- O RESTANTE FICA EXATAMENTE IGUAL ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.orm.jdbc.bind=TRACE
spring.jpa.open-in-view=true